# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-03-15 18:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('no', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='NO')),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=10, max_digits=20)),
            ],
        ),
    ]
