# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-03-20 17:24
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20200320_0655'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2020, 3, 20, 17, 24, 0, 358572, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
